"""Newton optimization logic independent from the Flet interface."""

from dataclasses import dataclass

import numpy as np
import sympy as sp


DEFAULT_TOLERANCE = 1e-6
DEFAULT_MAX_ITERATIONS = 14


@dataclass(frozen=True)
class NewtonResult:
    """Result and path generated by Newton's method."""

    expression: sp.Expr
    variables: tuple[sp.Symbol, sp.Symbol]
    point: np.ndarray
    history: tuple[np.ndarray, ...]
    converged: bool
    iterations: int


def solve_newton(
    expression_text: str,
    point_text: str,
    *,
    tolerance: float = DEFAULT_TOLERANCE,
    max_iterations: int = DEFAULT_MAX_ITERATIONS,
) -> NewtonResult:
    """Parse a two-variable function and minimize it using Newton's method."""
    expression, variables, point = _parse_problem(expression_text, point_text)
    gradient = [sp.diff(expression, variable) for variable in variables]
    hessian = [[sp.diff(component, variable) for variable in variables] for component in gradient]

    evaluate_gradient = sp.lambdify(variables, gradient, "numpy")
    evaluate_hessian = sp.lambdify(variables, hessian, "numpy")
    history = [point.copy()]

    for iteration in range(1, max_iterations + 1):
        gradient_value = _as_gradient(evaluate_gradient(*point))
        if np.linalg.norm(gradient_value) < tolerance:
            return _result(expression, variables, point, history, True, iteration - 1)

        hessian_value = _as_hessian(evaluate_hessian(*point))
        try:
            step = np.linalg.solve(hessian_value, -gradient_value)
        except np.linalg.LinAlgError as error:
            raise ValueError("La matriz Hessiana no es invertible en el punto actual.") from error

        if not np.all(np.isfinite(step)):
            raise ValueError("El método produjo un paso no finito.")

        point = point + step
        history.append(point.copy())

    gradient_value = _as_gradient(evaluate_gradient(*point))
    converged = bool(np.linalg.norm(gradient_value) < tolerance)
    return _result(expression, variables, point, history, converged, max_iterations)


def evaluate_surface(result: NewtonResult, x_values: np.ndarray, y_values: np.ndarray) -> np.ndarray:
    """Evaluate an optimization result expression over a two-dimensional mesh."""
    evaluate_function = sp.lambdify(result.variables, result.expression, "numpy")
    values = np.asarray(evaluate_function(x_values, y_values), dtype=float)
    if not np.all(np.isfinite(values)):
        raise ValueError("La función genera valores no finitos cerca del resultado.")
    return values


def _parse_problem(expression_text: str, point_text: str) -> tuple[sp.Expr, tuple[sp.Symbol, sp.Symbol], np.ndarray]:
    try:
        expression = sp.sympify(expression_text)
    except (sp.SympifyError, TypeError, ValueError) as error:
        raise ValueError("Escribe una función matemática válida.") from error

    variables = tuple(sorted(expression.free_symbols, key=lambda symbol: symbol.name))
    if len(variables) != 2:
        raise ValueError("La visualización 3D requiere exactamente dos variables, por ejemplo x e y.")

    values = [value.strip() for value in point_text.split(",")]
    if len(values) != 2 or not all(values):
        raise ValueError("Escribe el punto inicial con el formato x, y.")

    try:
        point = np.asarray([float(value) for value in values], dtype=float)
    except ValueError as error:
        raise ValueError("Las coordenadas del punto inicial deben ser números.") from error

    if not np.all(np.isfinite(point)):
        raise ValueError("Las coordenadas del punto inicial deben ser finitas.")

    return expression, (variables[0], variables[1]), point


def _as_gradient(value: object) -> np.ndarray:
    gradient = np.asarray(value, dtype=float).reshape(-1)
    if gradient.size != 2 or not np.all(np.isfinite(gradient)):
        raise ValueError("El gradiente no se puede evaluar en el punto actual.")
    return gradient


def _as_hessian(value: object) -> np.ndarray:
    hessian = np.asarray(value, dtype=float)
    if hessian.shape != (2, 2) or not np.all(np.isfinite(hessian)):
        raise ValueError("La Hessiana no se puede evaluar en el punto actual.")
    return hessian


def _result(
    expression: sp.Expr,
    variables: tuple[sp.Symbol, sp.Symbol],
    point: np.ndarray,
    history: list[np.ndarray],
    converged: bool,
    iterations: int,
) -> NewtonResult:
    return NewtonResult(
        expression=expression,
        variables=variables,
        point=point.copy(),
        history=tuple(item.copy() for item in history),
        converged=converged,
        iterations=iterations,
    )
